# The content in this file was generated by Gemini. It creates seed data for testing the database querying and semantic resolution.

import asyncio
import uuid
from database import SessionLocal, engine, Base
from models import TripHistory, SavedPlace
from datetime import datetime, timezone

async def seed_database():
    # Ensure tables exist (creates them if you haven't run Alembic/migrations)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with SessionLocal() as db:
        # Convert the string UUID to a Python UUID object for SQLAlchemy
        test_user_uuid = uuid.UUID("11111111-1111-1111-1111-111111111111")

        # 1. Seed a Semantic Location ("home")
        home_place = SavedPlace(
            user_id=test_user_uuid,
            label="home",
            latitude=15.5678,  
            longitude=150.1234 
        )
        
        # 2. Seed a Historical Trip (to DLSU)
        # Using the exact destination string the LLM extracts
        past_trip = TripHistory(
            user_id=test_user_uuid,
            destination_name="SM Manila",
            route_option="fastest",
            avoid_roads=["Edsa", "C5"],
            via_road_name="Taft Avenue",
            created_at=datetime.now(timezone.utc).replace(tzinfo=None)
        )

        db.add(home_place)
        db.add(past_trip)
        await db.commit()
        print(f"Database successfully seeded with test UUID {test_user_uuid} and updated schema!")

if __name__ == "__main__":
    asyncio.run(seed_database())